#pragma once

#include "CoreMinimal.h"
#include "SWTypes.h"

// ---------------------------------------------------------------------------
// Procedural geometry for the valley and the organisms. Everything the camera
// sees is generated here from the seeded look settings, so the scene is fully
// text-authored and reproducible: no hand-placed assets, no imported meshes.
// Materials are generated by Tools/make_materials.py; these buffers carry the
// vertex colours those materials read (R = emissive/marking mask, G = phase
// along the body, B = wetness on terrain).
// ---------------------------------------------------------------------------
namespace SWProc
{
	struct FMeshData
	{
		TArray<FVector> Verts;
		TArray<int32> Tris;
		TArray<FVector> Normals;
		TArray<FVector2D> UV0;
		TArray<FLinearColor> Colors;

		void Reserve(int32 V, int32 T) { Verts.Reserve(V); Normals.Reserve(V); UV0.Reserve(V); Colors.Reserve(V); Tris.Reserve(T); }
		int32 AddVert(const FVector& P, const FLinearColor& C, const FVector2D& UV = FVector2D::ZeroVector)
		{
			Verts.Add(P); Normals.Add(FVector::UpVector); UV0.Add(UV); Colors.Add(C); return Verts.Num() - 1;
		}
		void AddTri(int32 A, int32 B, int32 C) { Tris.Add(A); Tris.Add(B); Tris.Add(C); }
		void Append(const FMeshData& Other, const FTransform& Xf);
	};

	// Smooth per-vertex normals from the triangle list (area weighted).
	void ComputeNormals(FMeshData& M);

	// ---- Terrain field --------------------------------------------------
	// World-space ground height. Pure function of (X, Y) and the look settings
	// so agents can query it without touching the environment actor.
	float TerrainHeight(const FSWLookSettings& L, float X, float Y);
	float RiverCenterY(const FSWLookSettings& L, float X);
	// Height an organism stands at: ground, or water level when wading.
	float GroundZ(const FSWLookSettings& L, float X, float Y, float WaterDrop = 0.f);

	// ---- Builders ---------------------------------------------------------
	void BuildTerrain(const FSWLookSettings& L, FMeshData& Out);
	// Standing arch: a torus in the local XZ plane (opening faces +Y), half buried.
	void BuildArch(FRandomStream& Rng, float MajorR, float MinorR, float NoiseAmp, FMeshData& Out);
	// Massif arch (plate 1): a flat-topped sandstone bridge with thick tapering legs and a rounded
	// opening, lofted between an inner and an outer curve. Local space: the arch spans local X, the
	// opening axis is local Y, crown at z = TotalH, feet at z = 0 and extending to z = -0.25 * TotalH
	// so they bury on slopes. Vertex colour R = 1 on top-facing surfaces (moss mask). OutCrown receives
	// the extrados centreline samples with z >= 0.9 * TotalH (local space) for vegetation on the crown.
	void BuildMassifArch(FRandomStream& Rng, float OpenW, float OpenH, float TotalH, float DepthCrown, float DepthFoot,
	                     float LegW, float NoiseAmp, FMeshData& Out, TArray<FVector>* OutCrown = nullptr);
	// Boulder: displaced sphere.
	void BuildRock(FRandomStream& Rng, float Radius, float NoiseAmp, FMeshData& Out);
	// Organisms. Local +X is forward, +Z up, origin between the feet.
	void BuildLumen(FRandomStream& Rng, FMeshData& Out);
	void BuildTecton(FRandomStream& Rng, FMeshData& Out);
	// Leviathan: the river predator. NOT an organism — no genome, no learning, no
	// ESWSpecies entry; it belongs to the environment, like the drought. Local +X is
	// forward, +Z up, and the origin sits ON THE SPINE rather than between the feet
	// (it swims): the actor puts that origin below the water surface, so the dorsal
	// ridge cuts the surface when it rises.
	void BuildLeviathan(FRandomStream& Rng, FMeshData& Out);
	// Resource node: cluster of small glowing stones.
	void BuildGlowCluster(FRandomStream& Rng, float Radius, FMeshData& Out);

	// Primitive helpers (append into Out with a transform).
	void AppendEllipsoid(FMeshData& Out, const FTransform& Xf, const FVector& Radii, int32 Segs, int32 Rings,
	                     TFunctionRef<FLinearColor(const FVector& LocalUnit, const FVector& LocalPos)> ColorFn,
	                     TFunctionRef<float(const FVector& LocalUnit)> DisplaceFn);
	void AppendTaperedCylinder(FMeshData& Out, const FTransform& Xf, float R0, float R1, float Length, int32 Segs,
	                           const FLinearColor& C0, const FLinearColor& C1);
}
